if: tag IS blank
branches:
  only:
    - master
    - develop

language: node_js
node_js:
  - '10'

cache: yarn

install:
  - yarn install

script:
  - echo "No tests ran"

before_deploy:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/tmp/awscli-bundle.zip"
  - unzip /tmp/awscli-bundle.zip -d /tmp
  - /tmp/awscli-bundle/install -b $HOME/bin/aws
  - export PATH=$PATH:$HOME/bin

deploy:
  - provider: script
    script: ./.travis/deploy
    skip_cleanup: true
    on:
      branch:
        - master
        - develop
