version: '3'

services:
  troposphere:
    image: royal-borough-kingston/ck-client/troposphere
    build:
      context: ./docker/troposphere
      dockerfile: Dockerfile
    volumes:
      - ./aws:/tmp
    command: 'python ${CFN_TEMPLATE}.py'
