# Needs to be created in us-east-1
AWSTemplateFormatVersion: '2010-09-09'
Description: Create the lambda infrastructure needed to run the Hounslow Connect Frontend

Resources:

  LambdaSeoMetaFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: LambdaSeoMetaFunction

  LambdaSeoMetaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to insert correct meta tags for SEO and Open Graph
      Code:
        ZipFile: |
          'use strict';

          const AWS = require('aws-sdk');
          const s3 = new AWS.S3();
          const https = require('https');

          // Environment based endpoints
          const envUris = {
            apiBase: '',
            frontendBaseUrl: '',
            originalPath: ''
          };

          /*
          * Generate HTTP OK response using 200 status code with HTML body.
          */
          const response = {
              status: '200',
              statusDescription: 'OK',
              headers: {
                  'cache-control': [{
                      key: 'Cache-Control',
                      value: 'max-age=100'
                  }],
                  'content-type': [{
                      key: 'Content-Type',
                      value: 'text/html'
                  }]
              },
              body: null,
          };

          const pageMeta = {
            "home": [
              { name: '__PAGE_TITLE__', content: 'Home | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Home | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "results": [
              { name: '__PAGE_TITLE__', content: 'Results | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Results | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "favourites": [
              { name: '__PAGE_TITLE__', content: 'Favourites | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Favourites | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "referral": [
              { name: '__PAGE_TITLE__', content: 'Referral | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Referral | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "about": [
              { name: '__PAGE_TITLE__', content: 'About | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'About | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "contact": [
              { name: '__PAGE_TITLE__', content: 'Contact | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Contact | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "get-involved": [
              { name: '__PAGE_TITLE__', content: 'Get involved | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Get involved | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "privacy-policy": [
              { name: '__PAGE_TITLE__', content: 'Privacy policy | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Privacy policy | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalUrl}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "duty-to-refer": [
              { name: '__PAGE_TITLE__', content: 'Duty to refer | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Duty to refer | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalPath}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ],
            "terms-and-conditions": [
              { name: '__PAGE_TITLE__', content: 'Terms and Conditions | Hounslow Connect' },
              { name: '__PAGE_META_DESCRIPTION__', content:  'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' },
              { name: '__PAGE_META_OG_DESCRIPTION__', content: 'Hounslow Connect is a site dedicated to helping people find activities, join clubs, and navigate local services in Hounslow' }, { name: '__PAGE_META_OG_TITLE__', content: 'Terms and Conditions | Hounslow Connect' }, { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}${envUris.originalPath}` }, { name: '__PAGE_META_OG_IMAGE__', content: '' }
            ]
          };

          const getObject = async (bucket, objectKey) => {
            try {
              const params = {
                Bucket: bucket,
                Key: objectKey
              };
              const data = await s3.getObject(params).promise();

              return data.Body.toString('utf-8');
            } catch (e) {
              throw new Error(`Could not retrieve file from S3: ${e.message}`);
            }
          };

          const getApi = (url) => {
            return new Promise((resolve, reject) => {
              const options = {
                headers: {
                  'Accept': 'application/json',
                  'User-Agent': 'NodeHttp'
                }
              };
              https.get(url,options,(res) => {
                let body = "";

                res.on("data", (chunk) => {
                    body += chunk;
                });

                res.on("end", () => {
                    try {
                        let data = JSON.parse(body);
                        resolve(data);
                    } catch (error) {
                        reject(error.message);
                    }
                });

              }).on("error", (error) => {
                  reject(error.message);
              });
            });
          };

          const fetchService = async (name) => {
              try {
                  const response = await getApi(`${envUris.apiBase}/services/${name.trim()}`);
                  return response['data']? response['data'] : null;
              } catch (err) {
                console.log(err);
                  return false;
              }
          };

          const fetchOrganisation = async (name) => {
              try {
                  const response = await getApi(`${envUris.apiBase}/organisations/${name.trim()}`);
                  return response['data']? response['data'] : null;
              } catch (err) {
                console.log(err);
                  return false;
              }
          };

          const renderServiceMeta = async (slug) => {
            const data = await fetchService(slug);
            let metas = [];

            if(data) {
              metas = [
                  { name: '__PAGE_TITLE__', content: `${data.name} | Hounslow Connect` },
                  { name: '__PAGE_META_DESCRIPTION__', content:  `${data.intro}` },
                  { name: '__PAGE_META_OG_TITLE__', content: `${data.name}` },
                  { name: '__PAGE_META_OG_DESCRIPTION__', content: `${data.intro}` },
                  { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}/${data.slug}` },
                  { name: '__PAGE_META_OG_IMAGE__', content: (data.has_logo ? `${envUris.apiBase}/services/${data.id}/logo.png?` : `${envUris.apiBase}/organisations/${data.organisation_id}/logo.png?v=${data.organisation_id}`) }
              ];
            }

            return metas;
          };

          const renderOrganisationMeta = async (slug) => {
            const data = await fetchOrganisation(slug);
            let metas = [];

            if(data) {
              metas = [
                  { name: '__PAGE_TITLE__', content: `${data.name} | Hounslow Connect` },
                  { name: '__PAGE_META_DESCRIPTION__', content:  `${data.description}` },
                  { name: '__PAGE_META_OG_TITLE__', content: `${data.name}` },
                  { name: '__PAGE_META_OG_DESCRIPTION__', content: `${data.description}` },
                  { name: '__PAGE_META_OG_URL__', content: `${envUris.frontendBaseUrl}/${data.slug}` },
                  { name: '__PAGE_META_OG_IMAGE__', content: (data.has_logo ? `${envUris.apiBase}/organisations/${data.id}/logo.png?v=${data.id}` : '') }
              ];
            }

            return metas;
          };

          const renderMeta = async () => {
            const urlElements = envUris.originalPath.split('/');
            let meta = [];
            let slug = '';
            switch (urlElements[1]) {
              case 'services':
                if(! urlElements[2] || urlElements[2] === '') {
                  throw new Error('Missing slug');
                }
                slug = urlElements[2].trim();
                meta = await renderServiceMeta(slug);
                break;
              case 'organisations':
                if(! urlElements[2] || urlElements[2] === '') {
                  throw new Error('Missing slug');
                }
                slug = urlElements[2].trim();
                meta = await renderOrganisationMeta(slug);
                break;
              case 'results':
              case 'favourites':
              case 'referral':
              case 'about':
              case 'contact':
              case 'get-involved':
              case 'privacy-policy':
              case 'duty-to-refer':
              case 'terms-and-conditions':
                meta = pageMeta[urlElements[1]];
                break;
              default:
                meta = pageMeta['home'];
            }
            return meta;
          };

          const renderPage = async (bucket) => {
            try {
              let body = await getObject(bucket, 'index.html');
              const metas = await renderMeta();
              metas.forEach(meta => {
                if(meta.content !== '') {
                  body = body.replace(String(meta.name), `${meta.content}`);
                  return;
                }
                body = body.replace(String(meta.name), '');
              });
              // Return response
              response.body = body;
              return response;
            } catch(err) {
              console.log(err);
              response.body = err;
              response.status = 504;
              response.statusDescription = "Bad Gateway";
              return response;
            }
          };

          exports.handler = async (event, context, callback) => {

            // Extract the request from the CloudFront event that is sent to Lambda@Edge
            const request = event.Records[0].cf.request;

            if (! request.uri.endsWith('index.html') && request.uri.includes('.')) {
              // Return to CloudFront
              callback(null, request);
              return;
            }

            const domainName = request.origin.custom.customHeaders["x-env-cname"][0].value;
            envUris.frontendBaseUrl = `https://${domainName}`;
            envUris.apiBase = `https://api.${domainName}/core/v1`;
            envUris.originalPath = request.uri;

            const page = await renderPage(domainName);

            callback(null, page);
            return;
          };
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 15
      MemorySize: 1024
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn


  LambdaRedirectFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: LambdaRedirectFunction

  LambdaRedirectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function performing HTTP redirects
      Code:
        ZipFile: |
          'use strict';
          exports.handler = (event, context, callback) => {
            // Extract the request from the CloudFront event that is sent to Lambda@Edge
            const request = event.Records[0].cf.request;

            // Extract the URI from the request
            const oldUri = request.uri;
            let newUri = oldUri;
            let hasChanged = false;

            // Initialise the path mapping
            const map = {};

            // Rewrite URLs
            for (const [from, to] of Object.entries(map)) {
              const regex = new RegExp(`^(\\/${from})(\\/|\\/\\?.*|\\?.*)?$`);

              if (regex.test(newUri)) {
                hasChanged = true;
              }

              newUri = newUri.replace(from, to);
            }

            // Continue as normal
            if (!hasChanged) {
              return callback(null, request);
            }

            // Log the URI as received by CloudFront and the new URI to be used to fetch from origin
            console.log(`Old URI: ${oldUri}`);
            console.log(`New URI: ${newUri}`);

            // Create the redirect response
            const response = {
              status: '302',
              statusDescription: 'Found',
              headers: {
                location: [{
                  key: 'Location',
                  value: newUri,
                }],
              },
            };

            // Immediately return response to CloudFront
            return callback(null, response);
          };
      Handler: index.handler
      Runtime: nodejs12.x
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: s3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "AllowS3Access"
                Effect: "Allow"
                Action:
                  - s3:*
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
